# Form implementation generated from reading ui file 'ventana_citas.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaCitas(object):
    def setupUi(self, VentanaCitas):
        VentanaCitas.setObjectName("VentanaCitas")
        VentanaCitas.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=VentanaCitas)
        self.centralwidget.setObjectName("centralwidget")
        self.lbNombre = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbNombre.setGeometry(QtCore.QRect(30, 60, 141, 20))
        self.lbNombre.setStyleSheet("font: 700 12pt \"Segoe UI\";")
        self.lbNombre.setObjectName("lbNombre")
        self.lbApellido = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbApellido.setGeometry(QtCore.QRect(30, 110, 91, 20))
        self.lbApellido.setStyleSheet("font: 700 12pt \"Segoe UI\";")
        self.lbApellido.setObjectName("lbApellido")
        self.lbTlf = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbTlf.setGeometry(QtCore.QRect(30, 160, 101, 20))
        self.lbTlf.setStyleSheet("font: 700 12pt \"Segoe UI\";")
        self.lbTlf.setObjectName("lbTlf")
        self.lbfecha = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbfecha.setGeometry(QtCore.QRect(30, 210, 181, 20))
        self.lbfecha.setStyleSheet("font: 700 12pt \"Segoe UI\";")
        self.lbfecha.setObjectName("lbfecha")
        self.leNombre = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.leNombre.setGeometry(QtCore.QRect(410, 60, 361, 26))
        self.leNombre.setObjectName("leNombre")
        self.leApellido = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.leApellido.setGeometry(QtCore.QRect(410, 110, 361, 26))
        self.leApellido.setObjectName("leApellido")
        self.leTlf = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.leTlf.setGeometry(QtCore.QRect(410, 160, 361, 26))
        self.leTlf.setObjectName("leTlf")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.centralwidget)
        
        self.dateEdit.setGeometry(QtCore.QRect(410, 210, 361, 26))
        self.dateEdit.setKeyboardTracking(False)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.tabla = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tabla.setGeometry(QtCore.QRect(10, 280, 771, 231))
        self.tabla.setColumnCount(4)
        self.tabla.setObjectName("tabla")
        self.tabla.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(False)
        item.setFont(font)
        self.tabla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(3, item)
        self.tabla.horizontalHeader().setVisible(True)
        self.tabla.horizontalHeader().setCascadingSectionResizes(False)
        self.tabla.horizontalHeader().setDefaultSectionSize(150)
        self.tabla.horizontalHeader().setHighlightSections(False)
        self.tabla.horizontalHeader().setSortIndicatorShown(False)
        self.tabla.horizontalHeader().setStretchLastSection(True)
        self.tabla.verticalHeader().setVisible(True)
        self.btnAgregar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAgregar.setGeometry(QtCore.QRect(330, 530, 121, 41))
        self.btnAgregar.setStyleSheet("background-color: rgb(0, 123, 255);")
        self.btnAgregar.setObjectName("btnAgregar")
        VentanaCitas.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=VentanaCitas)
        self.statusbar.setObjectName("statusbar")
        VentanaCitas.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaCitas)
   
        QtCore.QMetaObject.connectSlotsByName(VentanaCitas)

    def retranslateUi(self, VentanaCitas):
        _translate = QtCore.QCoreApplication.translate
        VentanaCitas.setWindowTitle(_translate("VentanaCitas", "Agendar Cita Médica"))
        self.lbNombre.setText(_translate("VentanaCitas", "Nombre:"))
        self.lbApellido.setText(_translate("VentanaCitas", "Apellido: "))
        self.lbTlf.setText(_translate("VentanaCitas", "Teléfono"))
        self.lbfecha.setText(_translate("VentanaCitas", "Fecha de la cita: "))
        item = self.tabla.horizontalHeaderItem(0)
        item.setText(_translate("VentanaCitas", "Nombre"))
        item = self.tabla.horizontalHeaderItem(1)
        item.setText(_translate("VentanaCitas", "Apellido"))
        item = self.tabla.horizontalHeaderItem(2)
        item.setText(_translate("VentanaCitas", "Telefono"))
        item = self.tabla.horizontalHeaderItem(3)
        item.setText(_translate("VentanaCitas", "Fecha de Cita"))
        self.btnAgregar.setText(_translate("VentanaCitas", "Agregar Cita"))
        
